print("This is also a tests.")
print("Hello World!!!!")
print("Still practicing.")
print("This is kinda fun.")
print("And weird.")
print("But I like it.")
print("testing.")
print("testing.")
print("testing.")
print("testing.")
print("testing.")
print("testing.")